$(function(){
	//tela de programação screen 2 
	
	$(".php").hover(function(){
		$(".php").css({'left':'400px','top':'200px','transition':'2s','opacity':'1.0'});
	},function(){
		$(".php").css({'left':'320px','top':'170px','transition':'2s','opacity':'1.0'});
	});
	$(".axure").hover(function(){
		$(".axure").css({'right':'150px','top':'130px','transition':'2s','opacity':'1.0'});
	},function(){
		$(".axure").css({'right':'100px','top':'80px','transition':'2s','opacity':'1.0'});
	});
	$(".ajax").hover(function(){
		$(".ajax").css({'right':'50px','top':'350px','transition':'2s','opacity':'1.0'});
	},function(){
		$(".ajax").css({'right':'0px','top':'300px','transition':'2s','opacity':'1.0'});
	});
	$(".jquery").hover(function(){
		$(".jquery").css({'left':'150px','top':'130px','transition':'2s','opacity':'1.0'});
	},function(){
		$(".jquery").css({'left':'100px','top':'80px','transition':'2s','opacity':'1.0'});
	});
	$(".javascript").hover(function(){
		$(".javascript").css({'left':'370px','bottom':'150px','transition':'2s','opacity':'1.0'});
	},function(){
		$(".javascript").css({'left':'320px','bottom':'100px','transition':'2s','opacity':'1.0'});
	});
	$(".sql").hover(function(){
		$(".sql").css({'left':'370px','transition':'2s','opacity':'1.0'});
	},function(){
		$(".sql").css({'left':'320px','transition':'2s','opacity':'1.0'});
	});
	$(".sess").hover(function(){
		$(".sess").css({'left':'50px','top':'350px','transition':'2s','opacity':'1.0'});
	},function(){
		$(".sess").css({'left':'0px','top':'300px','transition':'2s','opacity':'1.0'});
	});
	// PHP
	$(".php").click(function(){
		$(".opening").hide();
		$(".text_php").show();
		$(".text_axure").hide();
		$(".text_ajax").hide();
		$(".text_jquery").hide();
		$(".text_javascript").hide();
		$(".text_sql").hide();
		$(".text_sess").hide();
		$('text_php_caf_1, .text_php_caf_2, .text_php_caf_3, .text_php_caf_4, .text_php_caf_5').hide();
		$('.black_screen2').css({'margin-right':'30px','margin-top':'2px','width':'400px'});
		setTimeout(function(){
			$('.black_screen2').animate({right:'0px',width:'10px'});
			$(".text_php_caf_1").show();
			setTimeout(function(){
				$('.black_screen2').css({'margin-right':'30px','margin-top':'22px','width':'400px'});
				$('.text_php_caf_2').show();
					setTimeout(function(){
						$('.black_screen2').animate({right:'0px',width:'10px'});
						$('.black_screen2').css({'margin-right':'30px','margin-top':'42px','width':'400px'});
						$('.text_php_caf_3').show();
						setTimeout(function(){
							$('.black_screen2').css({'float':'right','width':'10px'});
							$('.black_screen2').css({'margin-right':'30px','margin-top':'62px','width':'400px'});
							$('.text_php_caf_4').show();
							setTimeout(function(){
								$('.black_screen2').css({'float':'right','width':'40px','margin-right':'-20px'});
								$('.black_screen2').css({'margin-right':'30px','margin-top':'82px','width':'400px'});
								$('.text_php_caf_5').show();
								setTimeout(function(){
									$('.black_screen2').css({'float':'right','width':'40px','margin-right':'150px'});	
								},300);
							},300);		
						},300);	
					},300);
			},1500);
		},1500);
	});
	// Fim PHP 
	// axure
		$(".axure").click(function(){
		$(".opening").hide();
		$(".text_php").hide();
		$(".text_axure").show();
		$(".text_ajax").hide();
		$(".text_jquery").hide();
		$(".text_javascript").hide();
		$(".text_sql").hide();
		$(".text_sess").hide();
		$('text_axure_caf_1, .text_axure_caf_2, .text_axure_caf_3, .text_axure_caf_4').hide();
		$('.black_screen2').css({'margin-right':'10px','margin-top':'2px','width':'420px'});
		setTimeout(function(){
			$('.black_screen2').animate({right:'0px',width:'10px'});
			$(".text_axure_caf_1").show();
			setTimeout(function(){
				$('.black_screen2').css({'margin-right':'30px','margin-top':'22px','width':'400px'});
				$('.text_axure_caf_2').show();
					setTimeout(function(){
						$('.black_screen2').animate({right:'0px',width:'10px'});
						$('.black_screen2').css({'margin-right':'30px','margin-top':'42px','width':'400px'});
						$('.text_axure_caf_3').show();
						setTimeout(function(){
							$('.black_screen2').css({'margin-right':'30px','margin-top':'62px','width':'250px'});
							$('.black_screen2').animate({right:'0px',width:'250px'});
							$('.text_axure_caf_4').show();	
						},300);	
					},300);
			},1500);
		},1500);
	});
	// fim axure
	// ajax 
		$(".ajax").click(function(){
		$(".opening").hide();
		$(".text_php").hide();
		$(".text_axure").hide();
		$(".text_ajax").show();
		$(".text_jquery").hide();
		$(".text_javascript").hide();
		$(".text_sql").hide();
		$(".text_sess").hide();
		$('text_ajax_caf_1, .text_ajax_caf_2, .text_ajax_caf_3, .text_ajax_caf_4, .text_ajax_caf_5').hide();
		$('.black_screen2').css({'margin-right':'10px','margin-top':'2px','width':'420px'});
		setTimeout(function(){
			$('.black_screen2').animate({right:'0px',width:'10px'});
			$(".text_ajax_caf_1").show();
			setTimeout(function(){
				$('.black_screen2').css({'margin-right':'30px','margin-top':'22px','width':'400px'});
				$('.text_ajax_caf_2').show();
					setTimeout(function(){
						$('.black_screen2').animate({right:'0px',width:'10px'});
						$('.black_screen2').css({'margin-right':'30px','margin-top':'42px','width':'400px'});
						$('.text_ajax_caf_3').show();
						setTimeout(function(){
							$('.black_screen2').css({'float':'right','width':'10px'});
							$('.black_screen2').css({'margin-right':'30px','margin-top':'62px','width':'400px'});
							$('.text_ajax_caf_4').show();
							setTimeout(function(){
								$('.black_screen2').css({'margin-right':'30px','margin-top':'82px','width':'400px'});
								$('.black_screen2').animate({right:'0px',width:'280px'});
								$('.text_ajax_caf_5').show();
							},300);			
						},300);	
					},300);
			},1500);
		},1500);
	});
	// Fim ajax 
	//jquery
		$(".jquery").click(function(){
		$(".opening").hide();
		$(".text_php").hide();
		$(".text_axure").hide();
		$(".text_ajax").hide();
		$(".text_jquery").show();
		$(".text_javascript").hide();
		$(".text_sql").hide();
		$(".text_sess").hide();
		$('text_jquery_caf_1, .text_jquery_caf_2, .text_jquery_caf_3, .text_jquery_caf_4, .text_jquery_caf_5').hide();
		$('.black_screen2').css({'margin-right':'10px','margin-top':'2px','width':'420px'});
		setTimeout(function(){
			$('.black_screen2').animate({right:'0px',width:'10px'});
			$(".text_jquery_caf_1").show();
			setTimeout(function(){
				$('.black_screen2').css({'margin-right':'30px','margin-top':'22px','width':'400px'});
				$('.text_jquery_caf_2').show();
					setTimeout(function(){
						$('.black_screen2').animate({right:'0px',width:'10px'});
						$('.black_screen2').css({'margin-right':'30px','margin-top':'42px','width':'400px'});
						$('.text_jquery_caf_3').show();
						setTimeout(function(){
							$('.black_screen2').css({'float':'right','width':'10px'});
							$('.black_screen2').css({'margin-right':'30px','margin-top':'62px','width':'400px'});
							$('.text_jquery_caf_4').show();
							setTimeout(function(){
								$('.black_screen2').css({'margin-right':'30px','margin-top':'82px','width':'400px'});
								$('.black_screen2').animate({right:'0px',width:'120px'});
								$('.text_jquery_caf_5').show();
							},300);			
						},300);	
					},300);
			},1500);
		},1500);
	});
	//Fim jquery
	//javascript
		$(".javascript").click(function(){
		$(".opening").hide();
		$(".text_php").hide();
		$(".text_axure").hide();
		$(".text_ajax").hide();
		$(".text_jquery").hide();
		$(".text_javascript").show();
		$(".text_sql").hide();
		$(".text_sess").hide();
		$('text_javascript_caf_1, .text_javascript_caf_2, .text_javascript_caf_3, .text_javascript_caf_4, .text_javascript_caf_5').hide();
		$('.black_screen2').css({'margin-right':'10px','margin-top':'2px','width':'420px'});
		setTimeout(function(){
			$('.black_screen2').animate({right:'-10px',width:'10px'});
			$(".text_javascript_caf_1").show();
			setTimeout(function(){
				$('.black_screen2').css({'margin-right':'30px','margin-top':'22px','width':'400px'});
				$('.text_javascript_caf_2').show();
					setTimeout(function(){
						$('.black_screen2').animate({right:'0px',width:'10px'});
						$('.black_screen2').css({'margin-right':'30px','margin-top':'42px','width':'400px'});
						$('.text_javascript_caf_3').show();
						setTimeout(function(){
							$('.black_screen2').css({'float':'right','width':'10px'});
							$('.black_screen2').css({'margin-right':'30px','margin-top':'62px','width':'400px'});
							$('.text_javascript_caf_4').show();
							setTimeout(function(){
								$('.black_screen2').css({'margin-right':'30px','margin-top':'82px','width':'400px'});
								$('.black_screen2').animate({right:'0px',width:'50px'});
								$('.text_javascript_caf_5').show();
							},300);			
						},300);	
					},300);
			},1500);
		},1500);
	});
	// Fim javascript
	//sql
		$(".sql").click(function(){
		$(".opening").hide();
		$(".text_php").hide();
		$(".text_axure").hide();
		$(".text_ajax").hide();
		$(".text_jquery").hide();
		$(".text_javascript").hide();
		$(".text_sql").show();
		$(".text_sess").hide();
		$('text_sql_caf_1, .text_sql_caf_2, .text_sql_caf_3, .text_sql_caf_4, .text_sql_caf_5').hide();
		$('.black_screen2').css({'margin-right':'10px','margin-top':'2px','width':'420px'});
		setTimeout(function(){
			$('.black_screen2').animate({right:'-10px',width:'10px'});
			$(".text_sql_caf_1").show();
			setTimeout(function(){
				$('.black_screen2').css({'margin-right':'30px','margin-top':'22px','width':'400px'});
				$('.text_sql_caf_2').show();
					setTimeout(function(){
						$('.black_screen2').animate({right:'0px',width:'10px'});
						$('.black_screen2').css({'margin-right':'30px','margin-top':'42px','width':'400px'});
						$('.text_sql_caf_3').show();
						setTimeout(function(){
							$('.black_screen2').css({'margin-right':'30px','margin-top':'62px','width':'400px'});
							$('.black_screen2').animate({right:'0px',width:'130px'});
							$('.text_sql_caf_4').show();	
						},300);	
					},300);
			},1500);
		},1500);
	});
	//Fim sql
	// sass
		$(".sess").click(function(){
		$(".opening").hide();
		$(".text_php").hide();
		$(".text_axure").hide();
		$(".text_ajax").hide();
		$(".text_jquery").hide();
		$(".text_javascript").hide();
		$(".text_sql").hide();
		$(".text_sess").show();
		$('text_sass_caf_1, .text_sass_caf_2, .text_sass_caf_3, .text_sass_caf_4, .text_sass_caf_5').hide();
		$('.black_screen2').css({'margin-right':'10px','margin-top':'2px','width':'420px'});
		setTimeout(function(){
			$('.black_screen2').animate({right:'-10px',width:'10px'});
			$(".text_sass_caf_1").show();
			setTimeout(function(){
				$('.black_screen2').css({'margin-right':'30px','margin-top':'22px','width':'400px'});
				$('.text_sass_caf_2').show();
					setTimeout(function(){
						$('.black_screen2').animate({right:'0px',width:'10px'});
						$('.black_screen2').css({'margin-right':'30px','margin-top':'42px','width':'400px'});
						$('.text_sass_caf_3').show();
						setTimeout(function(){
							$('.black_screen2').css({'margin-right':'30px','margin-top':'62px','width':'400px'});
							$('.black_screen2').animate({right:'0px',width:'250px'});
							$('.text_sass_caf_4').show();	
						},300);	
					},300);
			},1500);
		},1500);
	});
	//fim sass
});